### ISSUE TITLE
Cannot resolve module 'paretojs' in webpack

### ISSUE THREAD

**Issue by patrickporto** [concretesolutions/pareto.js#10]
I'm using webpack 1.11.0. The library is installed and I try use:
```javascript
import _ from 'paretojs';
```
result:
```
Module not found: Error: Cannot resolve module 'paretojs'
```
how to solve?

**Comment by matheusml** [comment]
For some reason version 0.9.3 wasn't adding the lib and dist folder.
Please try reinstalling with the newest version (0.9.4) and trying again.

**Comment by patrickporto** [comment]
Oh great! 
but I try:
```javascript
var _ = require('paretojs')

console.log(_.equals({a: 1}, {a: 2}));
```
result:
```
TypeError: _.equals is not a function
```

**Comment by matheusml** [comment]
Version 0.9.8 should solve it.

**Comment by patrickporto** [comment]
great!
It's working in node, but not working in webpack with babel:
```javascript
import _ from 'paretojs';
console.log(_.equals({a: 1}, {a: 2}));
```
result:
```
TypeError: Cannot read property 'equals' of undefined
```

**Comment by matheusml** [comment]
Please download version 0.9.13.

You can now do it like this:

```js
import * as _ from 'paretojs';
```

Or only getting the method that you want:

```js
import { equals } from 'paretojs';
```

**Comment by patrickporto** [comment]
It's working!!!

thanks
